### ISSUE TITLE
Auto-update to new versions of postgresql?

### ISSUE THREAD

**Issue by Hoeze** [conda-forge/psqlodbc-feedstock#1]
Hi, there is already postgresql v12.3:
https://anaconda.org/conda-forge/postgresq
However, psqlodbc is still v11.

Would it be possible to keep this repository in sync with the postgresql package?

**Comment by spittssj** [comment]
I'm running into the same issue. Postgresql is now 13.1 but this package is still on 12.3.

**Comment by xhochy** [comment]
Please make a PR if you want a new version.

**Comment by cav71** [comment]
Hi, there's a a new version https://github.com/conda-forge/psqlodbc-feedstock/pull/2
